# Generated by Django 2.0.7 on 2018-07-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableedit',
            name='youth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
